# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
