# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0002_auto_20160806_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
